fos_rest:
  param_fetcher_listener:  true
  allowed_methods_listener:  true
  routing_loader: true
  view:
    view_response_listener:  true
  format_listener:
    enabled: true
    rules:
      - { path: '^/api/', prefer_extension: true, priorities: [ 'html' ] }
      - { path: '^/', prefer_extension: true, fallback_format: json, priorities: [ 'html' ] }
